# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.3
      - name: View poetry --help
        run: poetry --help
      - name: install dependencies
        run: poetry install
      - name: Create ENV folder
        run: mkdir ENV/
      - name: Add credentials.json file
        run: echo "${{ secrets.GOOGLE_API_CREDENTIALS }}" > ENV/credentials.json
        shell: bash
      - name: Run tests
        run: poetry run pytest
      - uses: pre-commit/action@v3.0.1
